### ISSUE TITLE
Chef windows_service resource errors CloseServiceHandle/close_service_handle

### ISSUE THREAD

**Issue by mbaitelman** [chef/win32-service#66]
[chef-stacktrace.txt](https://github.com/chef/win32-service/files/3087339/chef-stacktrace.txt)

## Description
The `windows_service` no longer works as expected when updating from Chef 14.11.21 to 14.12.3 
## Windows Version
Windows Server 21012r2

## Replication Case

           ================================================================================
           Error executing action `create` on resource 'windows_service[App]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `close_service_handle' for #<Win32::Service:0x000000000d10d5d0>
           Did you mean?  CloseServiceHandle

           Resource Declaration:
           ---------------------
           # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/corpchef/recipes/create_Appservice.rb

            39: windows_service 'App' do
            40:   binary_path_name           '"C:\java\App4\App.exe" -service -name "App" -App-home "C:\java\App"'
            41:   display_name               'App'
            42:   description                'App service for running corp systems. Managed by Chef'
            43:   #  run_as_password            String
            44:   #  run_as_user                String
            45:   startup_type               :automatic
            46:   action                     :create
            47:   not_if { ::File.exist?("#{Chef::Config[:file_cache_path]}/cheflock") }
            48: end
            49:

           Compiled Resource:
           ------------------
           # Declared in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/corpchef/recipes/create_Appservice.rb:39:in `from_file'

           windows_service("App") do
             action [:create]
             default_guard_interpreter :default
             service_name "App"
             enabled nil
             running nil
             masked nil
             pattern "App"
             declared_type :windows_service
             cookbook_name "corpchef"
             recipe_name "create_Appservice"
             startup_type :automatic
             binary_path_name "\"C:\\java\\App4\\App.exe\" -service -name \"App\" -App-home \"C:\\java\\App4\""
             display_name "App"
             not_if { #code block }
           end

           System Info:
           ------------
           chef_version=14.12.3
           platform=windows
           platform_version=6.3.9600
           ruby=ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client
           executable=C:/opscode/chef/bin/chef-client

**Comment by jasonwbarnett** [comment]
@mbaitelman Chef just released Chef Infra Client v14.12.9 which includes the fix to this problem. Thanks for reporting this problem and report back if you continue to have any other issues.

**Comment by mbaitelman** [comment]
Thank you. 
@tas50 sent it to me and Ive tested that it fixes the issue.
